name: Invero Build
#############################
on:
  push:
    branches: [ stable/v3 ]
  pull_request:
    branches: [ stable/v3 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: cache gradle packages
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        id: build_1
        run: ./gradlew build
      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build
      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TrMenu Artifact
          path: ./*
